services:
  - type: web
    name: video-chat-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://your-frontend-url.com 